# 안녕하세요^^ 
## '서울시 생활정보 기반 대중교통 수요 분석 ' 과정에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# 데이터 분석부터 먼저 시작해보겠습니다.
## "구별 업종 등록 데이터" 를 확인해 보도록 하겠습니다

In [1]:
# 필요 라이브러리부터 설치합니다.
%pip install pandas seaborn

Requirement already satisfied: pandas in c:\users\khh53\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: seaborn in c:\users\khh53\anaconda3\lib\site-packages (0.11.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\khh53\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\khh53\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\khh53\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: matplotlib>=2.2 in c:\users\khh53\anaconda3\lib\site-packages (from seaborn) (3.5.2)
Requirement already satisfied: scipy>=1.0 in c:\users\khh53\anaconda3\lib\site-packages (from seaborn) (1.7.3)
Requirement already satisfied: packaging>=20.0 in c:\users\khh53\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\khh53\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\khh53\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\khh53\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\khh53\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.25.0)
Requirement already satisfied: cycler>=0.10 in c:\users\khh53\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: six>=1.5 in c:\users\khh53\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

## 기본전제
* 처음에 제공되는 기본/추가 데이터는 'raw_data' 폴더에 있습니다.

[기본 데이터]
* business_type.csv

[데이터 소개]
* 서울 시 구별 등록 업종 상위 10개 데이터
    * 택시운송업
    * 한식일반음식점업
    * 용달 화물자동차 운송업
    * 부동산 중개 및 대리업
    * 두발미용업
    * 커피전문점
    * 남녀용 겉옷 및 셔츠 도매업
    * 기타주점업
    * 일반 교과 학원
    * 한식 육류요리 전문점

[변수 소개]
* 다수 업종 상위 1~10

---

# 1.데이터 불러오기
## 모든 미니 프로젝트의 시작은 '데이터 불러오기' 부터라고 할 수 있습니다.
+ KeyPoint : 불러오고자 하는 데이터에 따라 자유롭게 변수로 지정할 수 있다.

###  데이터 프레임을 불러오고 변수로 저장(여기서는 CSV 기준으로 진행)
* csv : pd.read_csv("파일이름. csv")
* txt : pd.read_csv("파일이름. csv", sep="구분자")
* xlsx : pd.read_excel('파일이름.xlsx')
* pickle : pd.read_pickle("파일이름.pkl") <br>
 [참고] pickle은 파이썬의 모든 객체를 파일로 저장할 수 있는 방법으로 DataFrame,List,Dict 등 모든 객체 저장 가능(특히 sklearn라이브러리를 통해 모델을 학습시키고, 저장할 때 많이 사용)

## 기본전제
* 처음에 제공되는 데이터는 'raw_data' 폴더에 있습니다.

[기본 데이터]
* 1.4 business_type.csv

[데이터 소개]
* 서울시 업종 등록 데이터

#### [실습문제1] 데이터 로딩
* '1.4 business_type.csv'파일을 'seoul_business' 변수에 저장하고 그 데이터를 확인하세요.
    * 데이터 파일 로딩시 참고 사항 
        * 구분자(sep)는 ',' 입니다
        * UTF-8 인코더를 사용해 주세요

In [2]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
import pandas as pd
seoul_business = pd.read_csv('1.4 business_type.csv', sep=",", encoding = "UTF-8", header =1, thousands = ',')

In [3]:
# 데이터 프레임의 Shape을 확인합니다.
seoul_business.shape

(450, 22)

In [4]:
for column in seoul_business:
    for i in range (len(seoul_business[column])):
        seoul_business[column][i]= seoul_business[column][i].replace(',','')

In [5]:
for column in seoul_business:
    for i in range (len(seoul_business[column])):
        seoul_business[column][i]= seoul_business[column][i].replace('-','0')

# 2.기본 정보 확인 및 클렌징

+ 데이터 클렌징 : 결측치, 이상치 등을 제거하여 데이터 분석 결과가 왜곡 되는 문제를 방지하기 위한 정제 과정

#### [실습문제2] 기본 정보 확인하기
* 'seoul_moving' 데이터의 정보를 확인해보세요.
* 'describe', 'info', 'head' 등 전부 활용해 보겠습니다.

In [6]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business.describe

<bound method NDFrame.describe of      자치구     동  택시운송업 택시운송업.1 한식 일반 음식점업 한식 일반 음식점업.1 용달 화물자동차 운송업  \
0    자치구     동   사업체수    종사자수       사업체수         종사자수         사업체수
1     합계    합계  47176   76701      29225       100183        28494
2    종로구    소계    215     215       1548         5912          618
3    종로구   사직동      7       7        230          982           12
4    종로구   삼청동      5       5         42          145            4
..   ...   ...    ...     ...        ...          ...          ...
445  강동구  성내3동    120     120        135          390           73
446  강동구  둔촌2동    117     436         63          249           89
447  강동구  암사1동    209     372         71          195          153
448  강동구  천호2동    157     187        152          509          144
449  강동구    길동   1441    1557        152          436          217

    용달 화물자동차 운송업.1 부동산 중개 및 대리업 부동산 중개 및 대리업.1  ...  커피전문점 커피전문점.1  \
0             종사자수         사업체수           종사자수  ...   사업체수    종사자수
1            29356        24013          42636  ...  16255   57322
2              646          549            889  ...    948    3613
3               12           57             96  ...    124     525
4                4            9             10  ...     66     243
..             ...          ...            ...  ...    ...     ...
445             73          104            163  ...     54     133
446             89           61            108  ...     34      85
447            153           67            107  ...     29      59
448            151           97            188  ...     63     212
449            225          146            237  ...     71     228

    남녀용 겉옷 및 셔츠 도매업 남녀용 겉옷 및 셔츠 도매업.1  기타주점업 기타주점업.1 일반 교과 학원 일반 교과 학원.1  \
0              사업체수              종사자수   사업체수    종사자수     사업체수       종사자수
1             13388             51116  13339   31371    11911      50773
2               400               962    537    1413      110        382
3                 2                18     74     177        9         34
4                 2                 3      3       8        0          0
..              ...               ...    ...     ...      ...        ...
445              10                86     57     103       66        199
446              10               788     21      39       35         90
447               3                 6     47      98       31         67
448               4                17     95     268       24         42
449               6               126    122     294       39        136

    한식 육류요리 전문점 한식 육류요리 전문점.1
0          사업체수          종사자수
1         11109         44653
2           437          1982
3            45           220
4             7            33
..          ...           ...
445          44           164
446          24           101
447          34            98
448          69           245
449          70           224

[450 rows x 22 columns]>

In [7]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business.info

<bound method DataFrame.info of      자치구     동  택시운송업 택시운송업.1 한식 일반 음식점업 한식 일반 음식점업.1 용달 화물자동차 운송업  \
0    자치구     동   사업체수    종사자수       사업체수         종사자수         사업체수
1     합계    합계  47176   76701      29225       100183        28494
2    종로구    소계    215     215       1548         5912          618
3    종로구   사직동      7       7        230          982           12
4    종로구   삼청동      5       5         42          145            4
..   ...   ...    ...     ...        ...          ...          ...
445  강동구  성내3동    120     120        135          390           73
446  강동구  둔촌2동    117     436         63          249           89
447  강동구  암사1동    209     372         71          195          153
448  강동구  천호2동    157     187        152          509          144
449  강동구    길동   1441    1557        152          436          217

    용달 화물자동차 운송업.1 부동산 중개 및 대리업 부동산 중개 및 대리업.1  ...  커피전문점 커피전문점.1  \
0             종사자수         사업체수           종사자수  ...   사업체수    종사자수
1            29356        24013          42636  ...  16255   57322
2              646          549            889  ...    948    3613
3               12           57             96  ...    124     525
4                4            9             10  ...     66     243
..             ...          ...            ...  ...    ...     ...
445             73          104            163  ...     54     133
446             89           61            108  ...     34      85
447            153           67            107  ...     29      59
448            151           97            188  ...     63     212
449            225          146            237  ...     71     228

    남녀용 겉옷 및 셔츠 도매업 남녀용 겉옷 및 셔츠 도매업.1  기타주점업 기타주점업.1 일반 교과 학원 일반 교과 학원.1  \
0              사업체수              종사자수   사업체수    종사자수     사업체수       종사자수
1             13388             51116  13339   31371    11911      50773
2               400               962    537    1413      110        382
3                 2                18     74     177        9         34
4                 2                 3      3       8        0          0
..              ...               ...    ...     ...      ...        ...
445              10                86     57     103       66        199
446              10               788     21      39       35         90
447               3                 6     47      98       31         67
448               4                17     95     268       24         42
449               6               126    122     294       39        136

    한식 육류요리 전문점 한식 육류요리 전문점.1
0          사업체수          종사자수
1         11109         44653
2           437          1982
3            45           220
4             7            33
..          ...           ...
445          44           164
446          24           101
447          34            98
448          69           245
449          70           224

[450 rows x 22 columns]>

In [8]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business.head

<bound method NDFrame.head of      자치구     동  택시운송업 택시운송업.1 한식 일반 음식점업 한식 일반 음식점업.1 용달 화물자동차 운송업  \
0    자치구     동   사업체수    종사자수       사업체수         종사자수         사업체수
1     합계    합계  47176   76701      29225       100183        28494
2    종로구    소계    215     215       1548         5912          618
3    종로구   사직동      7       7        230          982           12
4    종로구   삼청동      5       5         42          145            4
..   ...   ...    ...     ...        ...          ...          ...
445  강동구  성내3동    120     120        135          390           73
446  강동구  둔촌2동    117     436         63          249           89
447  강동구  암사1동    209     372         71          195          153
448  강동구  천호2동    157     187        152          509          144
449  강동구    길동   1441    1557        152          436          217

    용달 화물자동차 운송업.1 부동산 중개 및 대리업 부동산 중개 및 대리업.1  ...  커피전문점 커피전문점.1  \
0             종사자수         사업체수           종사자수  ...   사업체수    종사자수
1            29356        24013          42636  ...  16255   57322
2              646          549            889  ...    948    3613
3               12           57             96  ...    124     525
4                4            9             10  ...     66     243
..             ...          ...            ...  ...    ...     ...
445             73          104            163  ...     54     133
446             89           61            108  ...     34      85
447            153           67            107  ...     29      59
448            151           97            188  ...     63     212
449            225          146            237  ...     71     228

    남녀용 겉옷 및 셔츠 도매업 남녀용 겉옷 및 셔츠 도매업.1  기타주점업 기타주점업.1 일반 교과 학원 일반 교과 학원.1  \
0              사업체수              종사자수   사업체수    종사자수     사업체수       종사자수
1             13388             51116  13339   31371    11911      50773
2               400               962    537    1413      110        382
3                 2                18     74     177        9         34
4                 2                 3      3       8        0          0
..              ...               ...    ...     ...      ...        ...
445              10                86     57     103       66        199
446              10               788     21      39       35         90
447               3                 6     47      98       31         67
448               4                17     95     268       24         42
449               6               126    122     294       39        136

    한식 육류요리 전문점 한식 육류요리 전문점.1
0          사업체수          종사자수
1         11109         44653
2           437          1982
3            45           220
4             7            33
..          ...           ...
445          44           164
446          24           101
447          34            98
448          69           245
449          70           224

[450 rows x 22 columns]>

#### [실습문제3] 데이터 확인 및 처리

* 데이터를 보았을때, 어느 데이터를 가져와야 할지 생각 해 봅시다.

In [9]:
seoul_business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   자치구                450 non-null    object
 1   동                  450 non-null    object
 2   택시운송업              450 non-null    object
 3   택시운송업.1            450 non-null    object
 4   한식 일반 음식점업         450 non-null    object
 5   한식 일반 음식점업.1       450 non-null    object
 6   용달 화물자동차 운송업       450 non-null    object
 7   용달 화물자동차 운송업.1     450 non-null    object
 8   부동산 중개 및 대리업       450 non-null    object
 9   부동산 중개 및 대리업.1     450 non-null    object
 10  두발미용업              450 non-null    object
 11  두발미용업.1            450 non-null    object
 12  커피전문점              450 non-null    object
 13  커피전문점.1            450 non-null    object
 14  남녀용 겉옷 및 셔츠 도매업    450 non-null    object
 15  남녀용 겉옷 및 셔츠 도매업.1  450 non-null    object
 16  기타주점업              450 non-null    object
 17  기타주점업.1            450 non-null    object
 18  일반 교과 학원           450 non-null    object
 19  일반 교과 학원.1         450 non-null    object
 20  한식 육류요리 전문점        450 non-null    object
 21  한식 육류요리 전문점.1      450 non-null    object
dtypes: object(22)
memory usage: 77.5+ KB

In [10]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business

,자치구,동,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
0,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
1,합계,합계,47176,76701,29225,100183,28494,29356,24013,42636,...,16255,57322,13388,51116,13339,31371,11911,50773,11109,44653
2,종로구,소계,215,215,1548,5912,618,646,549,889,...,948,3613,400,962,537,1413,110,382,437,1982
3,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220
4,종로구,삼청동,5,5,42,145,4,4,9,10,...,66,243,2,3,3,8,0,0,7,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,강동구,성내3동,120,120,135,390,73,73,104,163,...,54,133,10,86,57,103,66,199,44,164
446,강동구,둔촌2동,117,436,63,249,89,89,61,108,...,34,85,10,788,21,39,35,90,24,101
447,강동구,암사1동,209,372,71,195,153,153,67,107,...,29,59,3,6,47,98,31,67,34,98
448,강동구,천호2동,157,187,152,509,144,151,97,188,...,63,212,4,17,95,268,24,42,69,245
449,강동구,길동,1441,1557,152,436,217,225,146,237,...,71,228,6,126,122,294,39,136,70,224

In [11]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   자치구                450 non-null    object
 1   동                  450 non-null    object
 2   택시운송업              450 non-null    object
 3   택시운송업.1            450 non-null    object
 4   한식 일반 음식점업         450 non-null    object
 5   한식 일반 음식점업.1       450 non-null    object
 6   용달 화물자동차 운송업       450 non-null    object
 7   용달 화물자동차 운송업.1     450 non-null    object
 8   부동산 중개 및 대리업       450 non-null    object
 9   부동산 중개 및 대리업.1     450 non-null    object
 10  두발미용업              450 non-null    object
 11  두발미용업.1            450 non-null    object
 12  커피전문점              450 non-null    object
 13  커피전문점.1            450 non-null    object
 14  남녀용 겉옷 및 셔츠 도매업    450 non-null    object
 15  남녀용 겉옷 및 셔츠 도매업.1  450 non-null    object
 16  기타주점업              450 non-null    object
 17  기타주점업.1            450 non-null    object
 18  일반 교과 학원           450 non-null    object
 19  일반 교과 학원.1         450 non-null    object
 20  한식 육류요리 전문점        450 non-null    object
 21  한식 육류요리 전문점.1      450 non-null    object
dtypes: object(22)
memory usage: 77.5+ KB

In [12]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_business.describe

<bound method NDFrame.describe of      자치구     동  택시운송업 택시운송업.1 한식 일반 음식점업 한식 일반 음식점업.1 용달 화물자동차 운송업  \
0    자치구     동   사업체수    종사자수       사업체수         종사자수         사업체수
1     합계    합계  47176   76701      29225       100183        28494
2    종로구    소계    215     215       1548         5912          618
3    종로구   사직동      7       7        230          982           12
4    종로구   삼청동      5       5         42          145            4
..   ...   ...    ...     ...        ...          ...          ...
445  강동구  성내3동    120     120        135          390           73
446  강동구  둔촌2동    117     436         63          249           89
447  강동구  암사1동    209     372         71          195          153
448  강동구  천호2동    157     187        152          509          144
449  강동구    길동   1441    1557        152          436          217

    용달 화물자동차 운송업.1 부동산 중개 및 대리업 부동산 중개 및 대리업.1  ...  커피전문점 커피전문점.1  \
0             종사자수         사업체수           종사자수  ...   사업체수    종사자수
1            29356        24013          42636  ...  16255   57322
2              646          549            889  ...    948    3613
3               12           57             96  ...    124     525
4                4            9             10  ...     66     243
..             ...          ...            ...  ...    ...     ...
445             73          104            163  ...     54     133
446             89           61            108  ...     34      85
447            153           67            107  ...     29      59
448            151           97            188  ...     63     212
449            225          146            237  ...     71     228

    남녀용 겉옷 및 셔츠 도매업 남녀용 겉옷 및 셔츠 도매업.1  기타주점업 기타주점업.1 일반 교과 학원 일반 교과 학원.1  \
0              사업체수              종사자수   사업체수    종사자수     사업체수       종사자수
1             13388             51116  13339   31371    11911      50773
2               400               962    537    1413      110        382
3                 2                18     74     177        9         34
4                 2                 3      3       8        0          0
..              ...               ...    ...     ...      ...        ...
445              10                86     57     103       66        199
446              10               788     21      39       35         90
447               3                 6     47      98       31         67
448               4                17     95     268       24         42
449               6               126    122     294       39        136

    한식 육류요리 전문점 한식 육류요리 전문점.1
0          사업체수          종사자수
1         11109         44653
2           437          1982
3            45           220
4             7            33
..          ...           ...
445          44           164
446          24           101
447          34            98
448          69           245
449          70           224

[450 rows x 22 columns]>

In [13]:
seoul_business.head(15)

,자치구,동,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
0,자치구,동,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
1,합계,합계,47176,76701,29225,100183,28494,29356,24013,42636,...,16255,57322,13388,51116,13339,31371,11911,50773,11109,44653
2,종로구,소계,215,215,1548,5912,618,646,549,889,...,948,3613,400,962,537,1413,110,382,437,1982
3,종로구,사직동,7,7,230,982,12,12,57,96,...,124,525,2,18,74,177,9,34,45,220
4,종로구,삼청동,5,5,42,145,4,4,9,10,...,66,243,2,3,3,8,0,0,7,33
5,종로구,부암동,22,22,26,100,9,9,17,26,...,24,62,3,6,7,23,16,59,3,15
6,종로구,평창동,10,10,31,116,11,11,33,52,...,19,62,2,4,26,54,25,71,10,103
7,종로구,무악동,10,10,10,26,410,416,12,17,...,7,15,0,0,0,0,14,50,1,2
8,종로구,교남동,14,14,14,44,7,7,26,37,...,13,55,0,0,1,1,5,22,3,15
9,종로구,가회동,9,9,57,270,7,7,16,23,...,46,133,2,2,5,9,3,10,6,21
10,종로구,종로1.2.3.4가동,1,1,565,2396,3,11,111,271,...,284,1360,210,376,237,674,8,50,192,996
11,종로구,종로5·6가동,6,6,176,542,11,25,71,84,...,72,197,71,192,36,74,0,0,51,204
12,종로구,이화동,4,4,71,395,17,17,13,13,...,69,338,9,127,27,108,2,14,11,45
13,종로구,창신1동,13,13,64,148,11,11,27,34,...,16,38,64,164,17,31,2,6,14,39
14,종로구,창신2동,16,16,37,89,24,24,13,15,...,9,22,3,7,9,14,1,6,19,42

In [14]:
seoul_business.drop(columns=['동'],inplace = True)
seoul_business.head(5)

,자치구,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,두발미용업,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
0,자치구,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,...,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수,사업체수,종사자수
1,합계,47176,76701,29225,100183,28494,29356,24013,42636,18080,...,16255,57322,13388,51116,13339,31371,11911,50773,11109,44653
2,종로구,215,215,1548,5912,618,646,549,889,261,...,948,3613,400,962,537,1413,110,382,437,1982
3,종로구,7,7,230,982,12,12,57,96,28,...,124,525,2,18,74,177,9,34,45,220
4,종로구,5,5,42,145,4,4,9,10,0,...,66,243,2,3,3,8,0,0,7,33

In [15]:
seoul_business.drop([0,1], axis=0, inplace = True)

In [16]:
seoul_business

,자치구,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,두발미용업,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
2,종로구,215,215,1548,5912,618,646,549,889,261,...,948,3613,400,962,537,1413,110,382,437,1982
3,종로구,7,7,230,982,12,12,57,96,28,...,124,525,2,18,74,177,9,34,45,220
4,종로구,5,5,42,145,4,4,9,10,0,...,66,243,2,3,3,8,0,0,7,33
5,종로구,22,22,26,100,9,9,17,26,8,...,24,62,3,6,7,23,16,59,3,15
6,종로구,10,10,31,116,11,11,33,52,19,...,19,62,2,4,26,54,25,71,10,103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445,강동구,120,120,135,390,73,73,104,163,83,...,54,133,10,86,57,103,66,199,44,164
446,강동구,117,436,63,249,89,89,61,108,62,...,34,85,10,788,21,39,35,90,24,101
447,강동구,209,372,71,195,153,153,67,107,82,...,29,59,3,6,47,98,31,67,34,98
448,강동구,157,187,152,509,144,151,97,188,83,...,63,212,4,17,95,268,24,42,69,245
449,강동구,1441,1557,152,436,217,225,146,237,121,...,71,228,6,126,122,294,39,136,70,224

In [17]:
seoul_business.columns

Index(['자치구', '택시운송업', '택시운송업.1', '한식 일반 음식점업', '한식 일반 음식점업.1', '용달 화물자동차 운송업',
       '용달 화물자동차 운송업.1', '부동산 중개 및 대리업', '부동산 중개 및 대리업.1', '두발미용업', '두발미용업.1',
       '커피전문점', '커피전문점.1', '남녀용 겉옷 및 셔츠 도매업', '남녀용 겉옷 및 셔츠 도매업.1', '기타주점업',
       '기타주점업.1', '일반 교과 학원', '일반 교과 학원.1', '한식 육류요리 전문점', '한식 육류요리 전문점.1'],
      dtype='object')

In [18]:
for column in seoul_business:
    if column == '자치구':
        continue
    seoul_business[column] = seoul_business[column].astype('int')

In [19]:
seoul_business = seoul_business.groupby(['자치구'], as_index=False).sum()

In [25]:
seoul_business.head(25)

,자치구,택시운송업,택시운송업.1,한식 일반 음식점업,한식 일반 음식점업.1,용달 화물자동차 운송업,용달 화물자동차 운송업.1,부동산 중개 및 대리업,부동산 중개 및 대리업.1,두발미용업,...,커피전문점,커피전문점.1,남녀용 겉옷 및 셔츠 도매업,남녀용 겉옷 및 셔츠 도매업.1,기타주점업,기타주점업.1,일반 교과 학원,일반 교과 학원.1,한식 육류요리 전문점,한식 육류요리 전문점.1
0,강남구,3592,5034,4830,22972,890,974,4674,13016,2482,...,3248,14546,768,16640,1426,5056,2852,18040,1654,10016
1,강동구,6590,9960,2202,6776,3056,3132,2376,3980,1800,...,1092,3320,118,2866,1178,2698,1240,4208,856,2918
2,강북구,3426,5178,1930,5326,2048,2060,1178,1734,1346,...,716,2190,80,188,1160,2550,440,1480,724,2352
3,강서구,7470,13844,2650,9168,3598,3724,2622,4704,2030,...,1380,5060,156,1400,1588,3418,1344,4694,1162,4548
4,관악구,2572,4054,2452,7378,3158,3200,2020,4272,1790,...,1162,4098,62,380,1316,3344,708,2460,844,3256
5,광진구,2238,3488,1926,5722,1936,1970,1742,2626,1492,...,1180,3774,178,1374,1266,3154,826,3292,934,3356
6,구로구,5514,7634,2096,6430,2636,2702,1578,2426,1458,...,842,2768,228,1846,1152,2330,672,2222,856,2992
7,금천구,2200,5196,1734,5238,1870,1994,1342,2762,976,...,766,2430,400,5150,782,1370,306,974,600,2084
8,노원구,8228,12148,1732,5300,3460,3472,1428,2106,1564,...,1070,3496,60,246,710,1688,1470,6562,856,3114
9,도봉구,5986,11566,1344,4018,3142,3148,1030,1588,1200,...,576,1674,44,86,516,954,702,2324,604,1886
10,동대문구,3092,4186,2472,7132,2862,2912,1684,2416,1222,...,988,2944,422,1952,998,2164,604,1968,884,3018
11,동작구,2066,2230,1530,4644,1660,1688,1766,2966,1302,...,972,3256,40,398,878,1910,814,2926,662,2354
12,마포구,2330,3676,2822,9410,1540,1658,2298,3806,1792,...,2738,8950,192,2418,2022,5118,938,3710,1402,5856
13,서대문구,3494,5354,1726,5388,1604,1616,1334,1912,1196,...,740,2646,44,136,994,2254,722,2536,622,2176
14,서초구,834,1806,3128,13424,772,822,2914,5516,1352,...,2024,7794,314,3126,892,2510,1624,7624,890,4676
15,성동구,2400,5054,1912,5570,2144,2322,1602,2906,978,...,1094,3718,298,3144,570,1242,516,2988,800,3090
16,성북구,3670,5286,1946,5644,2624,2670,1692,2350,1478,...,914,2768,170,908,1024,2060,928,3510,730,2668
17,송파구,5276,9700,3150,11520,3820,3862,3354,6380,2274,...,1950,6744,294,5660,1256,2938,1752,8320,1278,5562
18,양천구,5470,9884,1662,5600,2572,2586,1844,2728,1676,...,804,2750,50,104,830,1702,2568,11608,562,2222
19,영등포구,2698,4794,3476,12952,2562,2858,1972,3132,1346,...,1676,6590,152,2440,1272,2978,576,2164,988,4302
20,용산구,832,1046,1714,5974,910,932,1582,2428,732,...,1268,4152,108,634,974,2664,208,1146,600,2368
21,은평구,6216,8860,1762,5170,2680,2698,2268,3228,1894,...,914,2592,52,148,968,1850,1102,3586,952,3278
22,종로구,430,430,3096,11824,1236,1292,1098,1778,522,...,1896,7226,800,1924,1074,2826,220,764,874,3964
23,중구,460,470,3176,12828,600,666,1152,2304,678,...,1738,7084,21620,48496,762,1964,114,350,886,4242
24,중랑구,7268,12524,1982,4958,3608,3754,1476,2208,1580,...,762,2074,126,568,1070,2000,576,2090,998,3008

In [27]:
seoul_business.rename(columns = {'택시운송업' : '택시운송업 사업체수', '택시운송업.1' : '택시운송업 종사자수',
                               '한식 일반 음식점업' : '한식 일반 음식점업 사업체수','한식 일반 음식점업.1' : '한식 일반 음식점업 종사자수',
                               '용달 화물자동차 운송업': '용달 화물자동차 운송업 사업체수','용달 화물자동차 운송업.1' : '용달 화물자동차 운송업 종사자수',
                               '부동산 중개 및 대리업' : '부동산 중개 및 대리업 사업체수', '부동산 중개 및 대리업.1' : '부동산 중개 및 대리업 종사자수',
                               '두발미용업' : '두발미용업 사업체수', '두발미용업.1' : '두발미용업 종사자수',
                               '커피전문점' : '커피전문점 사업체수', '커피전문점.1' : '커피전문점 종사자수',
                               '남녀용 겉옷 및 셔츠 도매업' : '남녀용 겉옷 및 셔츠 도매업 사업체수', '남녀용 겉옷 및 셔츠 도매업.1' : '남녀용 겉옷 및 셔츠 도매업 종사자수',
                               '기타주점업' : '기타주점업 사업체수','기타주점업.1' : '기타주점업 종사자수',
                               '일반 교과 학원' : '일반 교과 학원 사업체수', '일반 교과 학원.1' : '일반 교과 학원 종사자수',
                               '한식 육류요리 전문점' : '한식 육류요리 전문점 사업체수', '한식 육류요리 전문점.1' : '한식 육류요리 전문점 종사자수'},inplace=True)

In [28]:
seoul_business.head(25)

,자치구,택시운송업 사업체수,택시운송업 종사자수,한식 일반 음식점업 사업체수,한식 일반 음식점업 종사자수,용달 화물자동차 운송업 사업체수,용달 화물자동차 운송업 종사자수,부동산 중개 및 대리업 사업체수,부동산 중개 및 대리업 종사자수,두발미용업 사업체수,...,커피전문점 사업체수,커피전문점 종사자수,남녀용 겉옷 및 셔츠 도매업 사업체수,남녀용 겉옷 및 셔츠 도매업 종사자수,기타주점업 사업체수,기타주점업 종사자수,일반 교과 학원 사업체수,일반 교과 학원 종사자수,한식 육류요리 전문점 사업체수,한식 육류요리 전문점 종사자수
0,강남구,3592,5034,4830,22972,890,974,4674,13016,2482,...,3248,14546,768,16640,1426,5056,2852,18040,1654,10016
1,강동구,6590,9960,2202,6776,3056,3132,2376,3980,1800,...,1092,3320,118,2866,1178,2698,1240,4208,856,2918
2,강북구,3426,5178,1930,5326,2048,2060,1178,1734,1346,...,716,2190,80,188,1160,2550,440,1480,724,2352
3,강서구,7470,13844,2650,9168,3598,3724,2622,4704,2030,...,1380,5060,156,1400,1588,3418,1344,4694,1162,4548
4,관악구,2572,4054,2452,7378,3158,3200,2020,4272,1790,...,1162,4098,62,380,1316,3344,708,2460,844,3256
5,광진구,2238,3488,1926,5722,1936,1970,1742,2626,1492,...,1180,3774,178,1374,1266,3154,826,3292,934,3356
6,구로구,5514,7634,2096,6430,2636,2702,1578,2426,1458,...,842,2768,228,1846,1152,2330,672,2222,856,2992
7,금천구,2200,5196,1734,5238,1870,1994,1342,2762,976,...,766,2430,400,5150,782,1370,306,974,600,2084
8,노원구,8228,12148,1732,5300,3460,3472,1428,2106,1564,...,1070,3496,60,246,710,1688,1470,6562,856,3114
9,도봉구,5986,11566,1344,4018,3142,3148,1030,1588,1200,...,576,1674,44,86,516,954,702,2324,604,1886
10,동대문구,3092,4186,2472,7132,2862,2912,1684,2416,1222,...,988,2944,422,1952,998,2164,604,1968,884,3018
11,동작구,2066,2230,1530,4644,1660,1688,1766,2966,1302,...,972,3256,40,398,878,1910,814,2926,662,2354
12,마포구,2330,3676,2822,9410,1540,1658,2298,3806,1792,...,2738,8950,192,2418,2022,5118,938,3710,1402,5856
13,서대문구,3494,5354,1726,5388,1604,1616,1334,1912,1196,...,740,2646,44,136,994,2254,722,2536,622,2176
14,서초구,834,1806,3128,13424,772,822,2914,5516,1352,...,2024,7794,314,3126,892,2510,1624,7624,890,4676
15,성동구,2400,5054,1912,5570,2144,2322,1602,2906,978,...,1094,3718,298,3144,570,1242,516,2988,800,3090
16,성북구,3670,5286,1946,5644,2624,2670,1692,2350,1478,...,914,2768,170,908,1024,2060,928,3510,730,2668
17,송파구,5276,9700,3150,11520,3820,3862,3354,6380,2274,...,1950,6744,294,5660,1256,2938,1752,8320,1278,5562
18,양천구,5470,9884,1662,5600,2572,2586,1844,2728,1676,...,804,2750,50,104,830,1702,2568,11608,562,2222
19,영등포구,2698,4794,3476,12952,2562,2858,1972,3132,1346,...,1676,6590,152,2440,1272,2978,576,2164,988,4302
20,용산구,832,1046,1714,5974,910,932,1582,2428,732,...,1268,4152,108,634,974,2664,208,1146,600,2368
21,은평구,6216,8860,1762,5170,2680,2698,2268,3228,1894,...,914,2592,52,148,968,1850,1102,3586,952,3278
22,종로구,430,430,3096,11824,1236,1292,1098,1778,522,...,1896,7226,800,1924,1074,2826,220,764,874,3964
23,중구,460,470,3176,12828,600,666,1152,2304,678,...,1738,7084,21620,48496,762,1964,114,350,886,4242
24,중랑구,7268,12524,1982,4958,3608,3754,1476,2208,1580,...,762,2074,126,568,1070,2000,576,2090,998,3008

In [29]:
# 해당 데이터프레임을 'df_seoul_business.csv' 파일로 저장하세요.
seoul_business.to_csv("df_seoul_business.csv", index = False)

---

# 3.데이터 분석하기
+ KeyPoint : 데이터의 형태를 살펴보고 다양한 분석기법을 통해 모델링에 적합하도록 정제요소를 선별할 수 있다.
  * 데이터들의 패턴 탐색
  * 변수들간의 관계 파악

In [30]:
# 시각화 한글폰트 설정
import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='nanum')
sns.set(font="NanumGothicCoding",#"NanumGothicCoding", 
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')

#### [실습문제4] 데이터 분포 알아보기
* 다양한 변수를 기준으로 그래프를 그려보고 인사이트를 도출해보세요.

In [22]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [23]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [24]:
# 위 차트를 통해 알게된 사실을 정리해봅시다.
# 1. 
# 2.
# 3.

---